# Generated by Django 4.0.5 on 2022-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mfforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('catagory', models.CharField(max_length=500)),
                ('village', models.CharField(max_length=50)),
            ],
        ),
    ]
