# Generated by Django 4.0.5 on 2022-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfforms',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='mfforms',
            name='village',
        ),
        migrations.AddField(
            model_name='mfforms',
            name='Address',
            field=models.TextField(default='fsadfasdfasdfasfasf', max_length=300),
        ),
        migrations.AddField(
            model_name='mfforms',
            name='Email',
            field=models.EmailField(default='ram@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='mfforms',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
